// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO0gARgAPxAKan_gKLP2DHnyYEB3qLJnc',
    appId: '1:311248955563:web:d706d718c4329795f92fee',
    messagingSenderId: '311248955563',
    projectId: 'graduation-3881d',
    authDomain: 'graduation-3881d.firebaseapp.com',
    storageBucket: 'graduation-3881d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSBgULF3z70EPqwaBS2ifc383PgH39YrM',
    appId: '1:311248955563:android:7ac3a7eb17a6af6ef92fee',
    messagingSenderId: '311248955563',
    projectId: 'graduation-3881d',
    storageBucket: 'graduation-3881d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe0hWGTPwdtFn_TCy1dF2EOk2qz5oAdiA',
    appId: '1:311248955563:ios:7d38580ef117835ef92fee',
    messagingSenderId: '311248955563',
    projectId: 'graduation-3881d',
    storageBucket: 'graduation-3881d.firebasestorage.app',
    iosBundleId: 'com.example.smartSportClub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe0hWGTPwdtFn_TCy1dF2EOk2qz5oAdiA',
    appId: '1:311248955563:ios:7d38580ef117835ef92fee',
    messagingSenderId: '311248955563',
    projectId: 'graduation-3881d',
    storageBucket: 'graduation-3881d.firebasestorage.app',
    iosBundleId: 'com.example.smartSportClub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBO0gARgAPxAKan_gKLP2DHnyYEB3qLJnc',
    appId: '1:311248955563:web:7e679589f2665065f92fee',
    messagingSenderId: '311248955563',
    projectId: 'graduation-3881d',
    authDomain: 'graduation-3881d.firebaseapp.com',
    storageBucket: 'graduation-3881d.firebasestorage.app',
  );
}
